name: Web E2E Tests - Trabalho final 

on: 
  workflow_dispatch:
  push:
     branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:

    # clone do projeto para a máquina
    - uses: actions/checkout@v4

    # conferir a versão instalada
    - name: Node version
      run: node --version

    # instalando dependências
    - name: Instalando dependências
      run: npm install

    # executando os testes
    - name: Executando os testes
      run: npx cypress run --spec "cypress/e2e/trabalho-final.cy.js"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled()}}
      with:
        name: relatorios
        path: | 
          cypress/reports
          cypress/screenshots
          cypress/videos
    
